---
apiVersion: v1
kind: ResourceQuota
metadata:
   name: BB-ResourceQuota
spec:
  hard:
    requests.cpu: '2'
    requests.memory: '2Gi'
    limits.cpu: '2'
    limits.memory: '4Gi'
    pods: '6'
    services: '5'