apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bb-statefulset

spec:
  serviceName: bb-statefulset
  replicas: 3

  selector:
    matchLabels:
      app: bb-stateful-app

  template:
    metadata:
      labels:
        app: bb-stateful-app

    spec:
      containers:
        - name: bb-stateful-container
          image: 465760686497.dkr.ecr.us-east-1.amazonaws.com/myrepo:dbimage

          ports:
            - containerPort: 80

          volumeMounts:
            - name: bb-storage
              mountPath: /data

  volumeClaimTemplates:
    - metadata:
        name: bb-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi
